// <auto-generated />
namespace Dexpa.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update075 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update075));
        
        string IMigrationMetadata.Id
        {
            get { return "201412030236326_Update075"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
