// <auto-generated />
namespace Dexpa.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update078 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update078));
        
        string IMigrationMetadata.Id
        {
            get { return "201412261336388_Update078"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
