// <auto-generated />
namespace Dexpa.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update014));
        
        string IMigrationMetadata.Id
        {
            get { return "201406241605538_Update014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
