// <auto-generated />
namespace Dexpa.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Update085 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update085));
        
        string IMigrationMetadata.Id
        {
            get { return "201502160720379_Update085"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
